apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-models-pvc
spec:
  storageClassName: hyperdisk-balanced-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
